name: Ontology CI

on:
  push:
    branches: ["master", "main"]
    paths: ["**.ttl", "**.rdf", "**.owl", "onto-ci.yml"]
  pull_request:
    branches: ["master", "main"]
    paths: ["**.ttl", "**.rdf", "**.owl", "onto-ci.yml"]

jobs:
  lint:
    name: Lint vocabulary files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gbelbe/semanticlint@v0.3.1
        with:
          path: "."
          fail-on: error
